branches:
  main

matrix:
  BUILDTYPE:
  # - "release"
  - "debug"

pipeline:
  build-env:
    image: alpine
    commands:
    - |
      apk add --no-cache git
      cd veloren
      git fetch --tags

      export VELOREN_GIT_TAG=$(git for-each-ref refs/tags --sort=-taggerdate --format='%(refname)' --count=2 | grep -ve 'nightly' | sed 's:refs/tags/::')
      echo "export VELOREN_VERSION=$VELOREN_GIT_TAG" >> .build_env
      echo "export VELOREN_COMMIT=$(git rev-parse --short $VELOREN_GIT_TAG)" >> .build_env

      # Set up build mode arguments and "latest" image tag for Docker
      if [ ${BUILDTYPE} == "release" ]; then
        echo "export VELOREN_BUILD_ARGS=--release" >> .build_env
        echo "export VELOREN_IMAGE_TAG=latest" >> .build_env
      else
        echo "export VELOREN_BUILD_ARGS=''" >> .build_env
        echo "export VELOREN_IMAGE_TAG='debug-latest'" >> .build_env
      fi

  build-images:
    image: jonoh/docker-buildx-qemu
    secrets:
      - DOCKERHUB_TOKEN
      - GITHUB_TOKEN
    environment:
      - PLATFORMS="linux/arm64/v8,linux/amd64"
      - IMAGE_NAME=veloren-server
      - DOCKERHUB_USERNAME=florianpiesche
      - GITHUB_USERNAME=fpiesche
    commands:
    - apt update; apt install -y jq
    - export DOCKERHUB_TOKEN=${DOCKERHUB_TOKEN}
    - export GITHUB_TOKEN=${GITHUB_TOKEN}
    - /bin/bash -x build-image.sh
