name: Nightly

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  PLATFORMS: linux/arm64/v8,linux/amd64
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' }}
  IMAGE_NAME: "veloren-server"

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Not doing Release builds because they straight up murder Github's build agents
        # BUILDTYPE: [ "debug", "release" ]
        BUILDTYPE: [ "debug" ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get current commit on submodule
        run: |
          echo VELOREN_COMMIT=$(git rev-parse --short @:./veloren) >> $GITHUB_ENV
          echo DATESTAMP=$(date +%Y.%m.%d) >> $GITHUB_ENV

      - name: Build and push ${{ env.IMAGE_NAME }} Docker image
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.BUILDTYPE }}.dockerfile
          build-args: |
            VELOREN_COMMIT=${{ env.VELOREN_COMMIT }}
            VELOREN_VERSION=${{ env.DATESTAMP }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/${{ env.IMAGE_NAME }}:${{ matrix.BUILDTYPE }}-nightly
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/${{ env.IMAGE_NAME }}:${{ matrix.BUILDTYPE }}-nightly-${{ env.DATESTAMP }}
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/${{ env.IMAGE_NAME }}:${{ matrix.BUILDTYPE }}-${{ env.VELOREN_COMMIT }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ matrix.BUILDTYPE }}-nightly
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ matrix.BUILDTYPE }}-nightly-${{ env.DATESTAMP }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ matrix.BUILDTYPE }}-${{ env.VELOREN_COMMIT }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
